### ISSUE TITLE
How to pass Mixed / Categorical Data?

### ISSUE THREAD

**Issue by kunind27** [tobinjo96/CPFcluster#2]
The paper mentions that the algorithm is for mixed, large datasets, though all the experiments shown are on datasets with numerical columns. Plus, the algorithm accepts only a numpy ndarray.

My question is, how do we input categorical / mixed data into the algorithm? Do we just do `pd.get_dummies()` on the pandas dataframe and then convert it to numpy, or is there any other way? 

I tried using the get dummies method, but the clustering results I got were really bad - with a lot of points being marked as outliers.

**Comment by Functional-Data-Clustering** [comment]
> The paper mentions that the algorithm is for mixed, large datasets, though all the experiments shown are on datasets with numerical columns. Plus, the algorithm accepts only a numpy ndarray.
> 
> My question is, how do we input categorical / mixed data into the algorithm? Do we just do `pd.get_dummies()` on the pandas dataframe and then convert it to numpy, or is there any other way?
> 
> I tried using the get dummies method, but the clustering results I got were really bad - with a lot of points being marked as outliers.

We are currently enhancing the package to support a distance matrix as input instead of a raw data matrix. This update will enable users to apply various distance calculation strategies tailored to different types of data. In our recent releast (version 3.0), we implemented the merge function, allowing users to merge similar clusters (but not outliers) into one.
